### ISSUE TITLE
代码高亮bug

### ISSUE THREAD

**Issue by scp-66** [lianginx/chatgpt-vue#5]
如果gpt回答中有代码，对话框中的代码没有高亮，```被正确显示

**Comment by lianginx** [comment]
这并不是Bug，因为我还没有做代码高亮，目前就是纯文本展示

**Comment by lianginx** [comment]
已增加Markdown渲染和代码高亮支持 https://github.com/lianginx/chatgpt-vue/commit/f7e912717c9ad48e72ce1e26695d5fb21f8cc74a
