### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by jiangyang118** [lianginx/chatgpt-vue#6]
SyntaxError: Unexpected end of JSON input
在对话框输入问题，返回的答案如上，请问还需要如何配置？

**Comment by lianginx** [comment]
不需要额外配置，只需要填入 API Key 就可以开始使用了。

看提示应该是 API 返回的数据没有被完整捕获并转换成 JSON，偶尔可能会遇到这个问题，大部分情况下应该都是正常的。

谢谢你的反馈，之后我会注意这个问题并尝试解决它。

**Comment by lianginx** [comment]
不好意思，我找到问题出在哪里了，已经处理这并提交 https://github.com/lianginx/chatgpt-vue/commit/158fa5effd29c3c7cc10225b7519767c953625fe
